[package]
name = "saturn_tagging"
version = "0.3.0"
authors = ["Phoebe Goldman <phoebe@goldman-tribe.org>"]
edition = "2018"
license = "MIT"

[dependencies.failure]
version = "0.1"
default_features = false # no `std`
features = ["derive"]

[features]
no_std = []

